services:
  rabbitmq:
    image: rabbitmq:4.1.1-management-alpine
    ports:
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5

  api_gateway_service:
    build: ./api_gateway_service
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      POSTS_SERVICE_URL: http://posts_service:8000
      CATEGORIES_SERVICE_URL: http://categories_service:8000
    depends_on:
      posts_service:
        condition: service_started
      categories_service:
        condition: service_started
    restart: on-failure

  posts_service:
    build: ./posts_service
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/posts.db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - posts_db_data:/app/data
    depends_on:
      categories_service:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  categories_service:
    build: ./categories_service
    environment:
      DATABASE_URL: sqlite+aiosqlite:///./data/categories.db
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    volumes:
      - categories_db_data:/app/data
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

volumes:
  posts_db_data:
  categories_db_data:
